"""Generate a LaTeX table of initial conditions for all simulation runs.

Columns: name, realizations, M_cloud, R_cloud, Z/Z_sun, Sigma, n_0, B_0.

Physics:
  Sigma = M / (pi * R^2)
  n_0   = 3M / (4 pi R^3 * mu_H * m_H)   [mu_H = 1.4, mean mass per H nucleus]
  B_0   from E_mag = bturb * |Egrav|, |Egrav| = 3GM^2/(5R)  [MakeCloud.py line 17+426]
         E_mag = B^2 R^3 / 6
         => B = M/R^2 * sqrt(18 * bturb * G / 5)
"""

import math

# Physical constants (CGS)
G    = 6.674e-8    # cm^3 g^-1 s^-2
mH   = 1.673e-24  # g
mu_H = 1.4         # mean mass per H nucleus (includes He)
Msun = 1.989e33   # g
pc   = 3.086e18   # cm

# Shared IC parameters encoded in all filenames
bturb = 0.1   # E_mag / |Egrav|  (B0.1 in MakeCloud.py --bturb)


def derived(M_msun, R_pc):
    M = M_msun * Msun
    R = R_pc * pc
    # surface density in M_sun/pc^2
    sigma = M_msun / (math.pi * R_pc**2)
    # mean number density
    rho = 3 * M / (4 * math.pi * R**3)
    n = rho / (mu_H * mH)
    # freefall time: standard uniform-sphere definition (matches MakeCloud.py line 250)
    rho = 3 * M / (4 * math.pi * R**3)
    t_ff_s = math.sqrt(3 * math.pi / (32 * G * rho))
    t_ff_Myr = t_ff_s / (3.156e13)  # s -> Myr
    # initial B field: E_mag = bturb * |Egrav|, |Egrav| = 3GM^2/(5R)
    # E_mag = B^2 R^3 / 6  =>  B = M/R^2 * sqrt(18 * bturb * G / 5)
    B_G = (M / R**2) * math.sqrt(18 * bturb * G / 5)
    B_uG = B_G * 1e6
    return sigma, n, t_ff_Myr, B_uG


runs = [
    # (label, physics, n_realizations, M_msun, R_pc, Z_solar, ISRF, CR)
    (r"\texttt{M2e4\_R10\_Z1}",    "Standard",                  8, 2e4, 10, 1.0,  1,     1),
    (r"\texttt{M2e4\_R10\_Z0.01}", "Standard",                  3, 2e4, 10, 0.01, 1,     1),
    (r"\texttt{M2e4\_R1\_Z1}",     "Standard",                  1, 2e4,  1, 1.0,  10000, 100),
    (r"\texttt{M2e4\_R1\_Z1}",     "No winds",                  1, 2e4,  1, 1.0,  10000, 100),
    (r"\texttt{M2e4\_R1\_Z1}",     r"No IR rad.\ pressure",     1, 2e4,  1, 1.0,  10000, 100),
    (r"\texttt{M2e4\_R1\_Z1}",     r"$3\times$ stronger winds", 1, 2e4,  1, 1.0,  10000, 100),
    (r"\texttt{M2e4\_R1\_Z0.1}",   "Standard",                  1, 2e4,  1, 0.1,  10000, 100),
    (r"\texttt{M2e4\_R1\_Z0.01}",  "Standard",                  1, 2e4,  1, 0.01, 10000, 100),
]

header = (
    r"Simulation & Physics & $N_{\rm real}$ & $M\,(M_\odot)$"
    r" & $R\,(\mathrm{pc})$ & $Z/Z_\odot$"
    r" & $\Sigma\,(M_\odot\,\mathrm{pc}^{-2})$"
    r" & $t_{\rm ff}\,(\mathrm{Myr})$"
    r" & $B_0\,(\mu\mathrm{G})$"
    r" & ISRF & Cosmic Rays"
    r" & $\Delta m\,(M_\odot)$ \\"
)

def radiation_str(val):
    exp = int(math.log10(val))
    return rf"$10^{{{exp}}}$" if val > 1 else "$1$"


def fmt(val, sigfigs=2):
    """sigfigs significant figures; scientific notation when more compact (|exp| >= 3)."""
    if val == 0:
        return "$0$"
    exp = int(math.floor(math.log10(abs(val))))
    # Round to sigfigs sig figs: position relative to decimal point
    sig_pos = exp - sigfigs + 1  # positive = round to 10^sig_pos, negative = decimal places
    rounded = round(val, -sig_pos)
    # Recompute exp in case rounding carried (e.g. 9.95 -> 10.0)
    exp = int(math.floor(math.log10(abs(rounded)))) if rounded != 0 else 0
    if exp >= 3 or exp <= -3:
        mantissa = rounded / 10**exp
        m_str = f"{mantissa:.{sigfigs-1}f}".rstrip("0").rstrip(".")
        if m_str == "1":
            return rf"$10^{{{exp}}}$"
        return rf"${m_str}\times10^{{{exp}}}$"
    else:
        decimal_places = max(0, -sig_pos)
        if decimal_places == 0:
            return f"${int(rounded)}$"
        return f"${rounded:.{decimal_places}f}$"


rows = []
for label, physics, n_real, M, R, Z, isrf, cr in runs:
    sigma, n, t_ff, B = derived(M, R)
    Z_str = f"${Z:g}$"
    M_str = r"$2\times10^{4}$"
    R_str = f"${R:g}$"
    rows.append(
        f"    {label} & {physics} & {n_real} & {M_str} & {R_str} & {Z_str}"
        f" & {fmt(sigma, 2)} & {fmt(t_ff, 2)} & {fmt(B, 2)}"
        f" & {radiation_str(isrf)} & {radiation_str(cr)} & $10^{{-3}}$ \\\\"
    )

table = r"""\begin{table*}[t!]
\centering
\begin{tabular}{llcccccccccc}
\toprule
""" + header + r"""
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\caption{Parameters for all simulations. $N_{\rm seed}$: number
of independent turbulent realizations. $M$: initial GMC mass. $R$: initial GMC radius. $\Sigma$: initial mean GMC surface density. $t_{\rm ff}$: cloud free-fall time based upon its initial mean density. $B_0$: strength of the initial uniform magnetic field. ISRF: scaling factor for the background interstellar radiation field, relative to the Solar neighborhood. Cosmic Rays: scaling factor for the background cosmic ray ionization rate relative to the Solar neighborhood. $\Delta m$: simulation mass resultion.}
\label{table:runs}
\end{table*}
"""

outpath = "tables/run_table.tex"
with open(outpath, "w") as f:
    f.write("% Auto-generated by tables/run_table.py -- do not edit by hand.\n")
    f.write(table)

print(table)
print(f"Written to {outpath}")
